services:
  mysql:
    ports: !reset []

  phpmyadmin:
    profiles: ['tools']
    ports: !override
      - '127.0.0.1:${PHPMYADMIN_PORT:-8080}:80'

  backend:
    build: !reset null
    image: ${BACKEND_IMAGE:-marleyk/oldtoms:backend-latest}
    pull_policy: always
    ports: !reset []
    restart: unless-stopped

  frontend:
    build: !reset null
    image: ${FRONTEND_IMAGE:-marleyk/oldtoms:frontend-latest}
    pull_policy: always
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports: !override
      - '${HTTP_PORT:-80}:80'
