# Generated by Django 3.2.25 on 2026-04-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for guest signatures', max_length=255)),
                ('message', models.TextField(help_text='A short message or signature')),
                ('image', models.ImageField(blank=True, null=True, upload_to='yearbook_images/')),
                ('is_badge', models.BooleanField(default=False, help_text='Set to true if this is a class badge/photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearbook_entries', to='alumni.alumni')),
            ],
            options={
                'verbose_name_plural': 'Yearbook Entries',
            },
        ),
    ]
