# Generated by Django 6.0.4 on 2026-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20260428_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated skills', max_length=500, null=True),
        ),
    ]
