# Generated by Django 3.2.25 on 2026-05-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_alter_alumni_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='art_work_description',
            field=models.TextField(blank=True, help_text='Description of your art or creative work', null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Link to art/work portfolio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
