# Generated by Django 3.2.25 on 2026-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
