# Generated by Django 6.0.4 on 2026-08-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_unique_event_registration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('host', 'Host school'), ('sister', 'Sister school')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='attendee_type',
            field=models.CharField(choices=[('legacy', 'Legacy registration'), ('old_student', 'Old student'), ('sister_school', 'Sister school guest'), ('other_school', 'Other school guest')], db_index=True, default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='batch_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='other_school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='roster_match_status',
            field=models.CharField(choices=[('pending', 'Pending database check'), ('matched', 'Matched in database'), ('not_found', 'Manual review required'), ('not_required', 'Not required')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='roster_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlumniRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('batch_year', models.PositiveSmallIntegerField(db_index=True)),
                ('alumni_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-batch_year', 'full_name'),
                'constraints': [models.UniqueConstraint(fields=('batch_year', 'email'), name='unique_roster_batch_email'), models.UniqueConstraint(fields=('batch_year', 'alumni_id'), name='unique_roster_batch_alumni_id')],
            },
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='matched_roster_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='alumni.alumnirosterentry'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to='alumni.school'),
        ),
    ]
